import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const origin = Deno.env.get('PUBLIC_SITE_ORIGIN') || 'https://privatewindow.web.app'
const cors = { 'Access-Control-Allow-Origin': origin, 'Access-Control-Allow-Headers': 'authorization, apikey, content-type, x-admin-key', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS', 'Cache-Control': 'no-store' }
const json = (value: unknown, status = 200) => new Response(JSON.stringify(value), { status, headers: { ...cors, 'Content-Type': 'application/json' } })
const db = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!, { auth: { persistSession: false } })
const enc = new TextEncoder()
const hex = (bytes: Uint8Array) => [...bytes].map((byte) => byte.toString(16).padStart(2, '0')).join('')
const randomHex = (count = 4) => hex(crypto.getRandomValues(new Uint8Array(count))).toUpperCase()
const rawKey = (plan: string) => `PW-${plan.toUpperCase()}-${randomHex()}-${randomHex()}-${randomHex()}`
const b64 = (bytes: Uint8Array) => btoa(String.fromCharCode(...bytes))
async function hash(value: string) { return hex(new Uint8Array(await crypto.subtle.digest('SHA-256', enc.encode(value.trim().toUpperCase())))) }
async function aesKey() {
  const bytes = Uint8Array.from(atob(Deno.env.get('LICENSE_ENCRYPTION_KEY') || ''), (char) => char.charCodeAt(0))
  if (bytes.length !== 32) throw new Error('LICENSE_ENCRYPTION_KEY must be a base64-encoded 32-byte value')
  return crypto.subtle.importKey('raw', bytes, 'AES-GCM', false, ['encrypt', 'decrypt'])
}
async function encrypt(value: string) { const iv = crypto.getRandomValues(new Uint8Array(12)); const data = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, await aesKey(), enc.encode(value))); return `${b64(iv)}.${b64(data)}` }
async function decrypt(value: string) { const [iv, data] = value.split('.').map((part) => Uint8Array.from(atob(part), (char) => char.charCodeAt(0))); return new TextDecoder().decode(await crypto.subtle.decrypt({ name: 'AES-GCM', iv }, await aesKey(), data)) }
async function token(payload: Record<string, unknown>) { const body = b64(enc.encode(JSON.stringify(payload))).replaceAll('+', '-').replaceAll('/', '_').replaceAll('=', ''); const key = await crypto.subtle.importKey('raw', enc.encode(Deno.env.get('ENTITLEMENT_SIGNING_KEY') || ''), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']); const signature = b64(new Uint8Array(await crypto.subtle.sign('HMAC', key, enc.encode(body)))).replaceAll('+', '-').replaceAll('/', '_').replaceAll('=', ''); return `${body}.${signature}` }
async function body(req: Request) { try { return await req.json() } catch { return {} } }
async function user(req: Request) { const bearer = req.headers.get('Authorization')?.replace(/^Bearer\s+/i, ''); if (!bearer) return null; const result = await db.auth.getUser(bearer); return result.error ? null : result.data.user }
function admin(req: Request) { const a = req.headers.get('X-Admin-Key') || ''; const b = Deno.env.get('LICENSE_ADMIN_KEY') || ''; if (!a || a.length !== b.length) return false; let different = 0; for (let i = 0; i < a.length; ++i) different |= a.charCodeAt(i) ^ b.charCodeAt(i); return different === 0 }
async function findUser(email: string) { for (let page = 1; page <= 20; ++page) { const result = await db.auth.admin.listUsers({ page, perPage: 1000 }); if (result.error) throw result.error; const found = result.data.users.find((item) => item.email?.toLowerCase() === email.toLowerCase()); if (found) return found; if (result.data.users.length < 1000) break } return null }
async function issue(ownerId: string, email: string, planId: string, provider = 'manual') {
  const plans = await db.from('license_plans').select('*').eq('id', planId).eq('active', true).single(); if (plans.error) throw plans.error
  const key = rawKey(planId); const created = await db.from('licenses').insert({ key_hash: await hash(key), key_ciphertext: await encrypt(key), owner_id: ownerId, owner_email: email, plan_id: planId, max_devices: plans.data.max_devices, annual_transfer_limit: plans.data.annual_transfer_limit, provider }).select('id').single(); if (created.error) throw created.error
  return { id: created.data.id, key, tier: planId, max_devices: plans.data.max_devices }
}
async function adminIssue(req: Request) { if (!admin(req)) return json({ message: 'Administrator authorization failed.' }, 401); const data = await body(req); const email = String(data.email || '').trim(); const plan = String(data.plan_id || '').trim(); if (!email || !['single', 'pro', 'power', 'free'].includes(plan)) return json({ message: 'A valid account email and plan are required.' }, 400); const owner = await findUser(email); if (!owner) return json({ message: 'No account exists for that email. Ask the customer to sign in first.' }, 404); return json({ license: await issue(owner.id, owner.email || email, plan) }, 201) }
async function freeKey(req: Request) { const owner = await user(req); if (!owner) return json({ message: 'Sign in to request a free key.' }, 401); if (Deno.env.get('FREE_KEYS_ENABLED') !== 'true') return json({ message: 'The free-key promotion is not available.' }, 410); const existing = await db.from('licenses').select('id').eq('owner_id', owner.id).eq('plan_id', 'free').limit(1); if (existing.data?.length) return json({ message: 'This account already has a free key.' }, 409); return json({ license: await issue(owner.id, owner.email || '', 'free', 'promotion') }, 201) }
async function licenses(req: Request) { const owner = await user(req); if (!owner) return json({ message: 'Sign in to view licenses.' }, 401); const result = await db.from('licenses').select('id,key_ciphertext,plan_id,status,max_devices,annual_transfer_limit,transfers_used,created_at,license_devices(id,device_name,active,first_seen_at,last_seen_at)').eq('owner_id', owner.id).order('created_at', { ascending: false }); if (result.error) throw result.error; return json({ licenses: await Promise.all((result.data || []).map(async (license) => ({ id: license.id, key: await decrypt(license.key_ciphertext), tier: license.plan_id, status: license.status, max_devices: license.max_devices, transfers_remaining: license.annual_transfer_limit === null ? null : Math.max(0, license.annual_transfer_limit - license.transfers_used), devices: license.license_devices, created_at: license.created_at }))) }) }
async function check(req: Request) { const owner = await user(req); if (!owner) return json({ valid: false, message: 'Sign in to validate a key.' }, 401); const data = await body(req); const result = await db.from('licenses').select('plan_id,status,max_devices').eq('key_hash', await hash(String(data.license_key || ''))).eq('owner_id', owner.id).maybeSingle(); return result.data ? json({ valid: result.data.status === 'active', tier: result.data.plan_id, status: result.data.status, max_devices: result.data.max_devices }) : json({ valid: false, message: 'This key was not found in your account.' }, 404) }
async function activate(req: Request) { const data = await body(req); const device = String(data.device_id || ''); if (!data.license_key || !/^[a-f0-9]{64}$/i.test(device)) return json({ valid: false, message: 'A license key and valid device identifier are required.' }, 400); const result = await db.rpc('activate_license', { p_key_hash: await hash(String(data.license_key)), p_hwid_hash: device, p_device_name: String(data.device_name || 'Windows PC').slice(0, 80) }); if (result.error) throw result.error; if (!result.data.valid) return json(result.data, result.data.code === 'invalid_key' ? 401 : 403); return json({ ...result.data, expires_at: null, entitlement_token: await token({ license_id: result.data.license_id, tier: result.data.tier, device_id: device, issued_at: Date.now() }) }) }
async function deactivate(req: Request) { const data = await body(req); const result = await db.rpc('deactivate_license_device', { p_key_hash: await hash(String(data.license_key || '')), p_hwid_hash: String(data.device_id || '') }); if (result.error) throw result.error; return json({ deactivated: Boolean(result.data) }) }
async function unbind(req: Request) { const owner = await user(req); if (!owner) return json({ message: 'Sign in to manage devices.' }, 401); const data = await body(req); const result = await db.rpc('unbind_license_device', { p_license_id: data.license_id, p_device_id: data.device_id, p_owner_id: owner.id }); if (result.error) throw result.error; return json({ unbound: Boolean(result.data) }, result.data ? 200 : 404) }
async function startTrial(req: Request) { const data = await body(req); const device = String(data.device_id || ''); if (!/^[a-f0-9]{64}$/i.test(device)) return json({ message: 'Invalid device identifier.' }, 400); const session = `${randomHex(16)}${randomHex(16)}`; const result = await db.rpc('start_trial', { p_hwid_hash: device, p_token_hash: await hash(session) }); if (result.error) throw result.error; return json({ ...result.data, session_token: session, heartbeat_seconds: 30 }) }
async function heartbeat(req: Request) { const data = await body(req); const result = await db.rpc('heartbeat_trial', { p_hwid_hash: String(data.device_id || ''), p_token_hash: await hash(String(data.session_token || '')) }); if (result.error) return json({ expired: true, remaining_seconds: 0, message: 'Trial session is invalid.' }, 403); return json(result.data) }

Deno.serve(async (req) => { if (req.method === 'OPTIONS') return new Response(null, { headers: cors }); try { const path = new URL(req.url).pathname.replace(/^\/(?:functions\/v1\/)?licensing/, ''); if (req.method === 'POST' && path === '/v1/admin/licenses/issue') return adminIssue(req); if (req.method === 'POST' && path === '/v1/licenses/free') return freeKey(req); if (req.method === 'GET' && path === '/v1/account/licenses') return licenses(req); if (req.method === 'POST' && path === '/v1/licenses/check') return check(req); if (req.method === 'POST' && path === '/v1/licenses/activate') return activate(req); if (req.method === 'POST' && path === '/v1/licenses/deactivate') return deactivate(req); if (req.method === 'POST' && path === '/v1/account/unbind') return unbind(req); if (req.method === 'POST' && path === '/v1/trial/start') return startTrial(req); if (req.method === 'POST' && path === '/v1/trial/heartbeat') return heartbeat(req); return json({ message: 'Not found.' }, 404) } catch (error) { console.error(error); return json({ message: 'The licensing service could not complete this request.' }, 500) } })
